# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_date', models.DateField()),
                ('group_hour', models.TimeField()),
                ('price', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, unique=True)),
                ('year_of_birth', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=20)),
                ('phone_number', models.CharField(max_length=200)),
                ('default_price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('how_arrived', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=200)),
                ('is_trainee', models.CharField(max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('comments', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('receipt_num', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('cheque', 'Cheque'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('other', 'Other')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('main_concern', models.CharField(max_length=200)),
                ('what_we_did', models.CharField(max_length=200)),
                ('home_work', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Patient'),
        ),
    ]
